### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by Sondro** [datakurre/gatsby-starter-plone-brochure#1]
Hi, I just found this repo and wanted to test it out.

With docker-machine I got Plone up and running at http://http://192.168.99.100:8080/Plone/

However  I wasn't able to get the gatsby demo to work at http://localhost:8080/Plone/example/ (Chrome browser error: "localhost refused to connect").

 Or... 

http://192.168.99.100:8080/Plone/example (Plone: 'This page does not seem to exist...').

There's an error from docker-compose saying ```INFO twisted Timing out client: IPv4Address(type='TCP', host='192.168.99.1', port=51960')```

I think it might be a bad gateway error with port or IP not configured properly. I"m not sure how it's supposed to be properly configured though.

Any ideas? 

This is what my docker and gatsby terminals look like:
![error](https://user-images.githubusercontent.com/1184976/86069871-013a0e80-ba30-11ea-85ed-bc22c7c7b2ac.jpg)

**Comment by datakurre** [comment]
Hi, did you fix configuration in gatsby-config.js to point `http://192.168.99.100:8080/Plone/` instead of `http://localhost:8080/Plone/`?

I tried on a Linux environment that everything still works as advertised. A possible another issue on Windows is that the demo starts empty and the example data population scripts (purge and import) in README are designed to work in Linux only.

**Comment by datakurre** [comment]
Of course the example data can also be created manually. I recall that it was simply published folder named "Example" and content (pages, folders, images) below it (and this example composed a single page out of those).

https://datakurre.github.io/gatsby-starter-plone-brochure/

**Comment by Sondro** [comment]
Thx for the response. I manually replaced all `http://localhost:8080` to `http://192.168.99.100:8080`

For the purge/import.sh bash files, I then installed jq manually with choclately using `choco install jq`.

This gives me a `docker-compose` that looks like it's working here, although the type is missing:
![docker-compose_00](https://user-images.githubusercontent.com/1184976/86138692-a0e4b480-baa3-11ea-97c4-30dc2bb9ac9d.jpg)

However, with `yarn develop` I'm getting all these errors (because the type is missing?):
![error_00](https://user-images.githubusercontent.com/1184976/86138772-b954cf00-baa3-11ea-96f4-725309a9ab88.jpg)

I made a copy and tried `yarn upgrade`, but then it wanted the gatsby-node.js to be uncommented and was complaining those files were missing.

**Comment by datakurre** [comment]
I'm sorry for the way too long silence. For anyone founding this issue: I have now added required type definitions to avoid GatsbyJS from failing for GraphQL errors when the example site does not have expected content. Unfortunately, the scripts for populating the example site running in the Docker don't work on Windows.

**Comment by Sondro** [comment]
Thanks for the response. I think I'll check out Volto next. I noticed you did a demo repo (https://github.com/datakurre/my-volto-app), feel free to share any tips or differences bewteen gatsby-plone and Volto here and I'll close the thread. 

Thanks again.
